### ISSUE TITLE
Google map api?

### ISSUE THREAD

**Issue by carlsendk** [thriveweb/yellowcake#37]
Where to put google map api key?

**Comment by xstable** [comment]
Found it in src/components/googlemaps.js:

```
let mapkey = ''
if (process.env.NETLIFY_MAP_KEY) {
  mapkey = process.env.NETLIFY_MAP_KEY
}
```
So you have to set it via ENV-Variable on Netlify.


@thrivedevteam BTW. no clean solution to implement. For example if you use Gitlab, there isn't an NETLIFY_MAP_KEY Enviroment-Variable.
I even would prefer to use https://leafletjs.com/ (see https://www.gatsbyjs.org/packages/gatsby-plugin-react-leaflet/?=leaflet)  instead of google-maps. Because leafletjs is free to use.
With Goggle-maps you can run in surprising charges, if you use more then the monthly free tier ($200) of google!

**Comment by Firthir** [comment]
This is a feature within Netlify environment variables.
These are accessible during your build. This allows you to change behaviors based on deploy parameters or to include information you don't want to save in your repository, such as API keys.
https://docs.netlify.com/configure-builds/environment-variables/

https://leafletjs.com/ looks good make a pull request @xstable and we will review it :)
